cc_binary(
    name = "file-test",
    srcs = ["file-test.cc"],
    deps = [
    ],
)

cc_binary(
    name = "getline-benchmark",
    srcs = ["getline-benchmark.cc"],
    deps = [
        "@com_google_benchmark//:benchmark_main",
    ],
)