cc_test(
    name = "binary_search_test",
    size = "small",
    srcs = ["binary_search_test.cc", "binary_search.h"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "binary_search_benchmark",
    srcs = ["binary_search_benchmark.cc", "binary_search.h"],
    deps = ["@com_google_benchmark//:benchmark_main"],
)
